// <auto-generated />
using ImpactHub.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ImpactHub.Data.Migrations
{
    [DbContext(typeof(ImpactHubDbContext))]
    [Migration("20240915002605_InitialMapping")]
    partial class InitialMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImpactHub.Business.Models.CadastroModel", b =>
                {
                    b.Property<int>("IdCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCadastro"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("DataAbertura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("IdLogin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(180)");

                    b.HasKey("IdCadastro");

                    b.ToTable("TB_IMPACTHUB_CADASTRO", (string)null);
                });

            modelBuilder.Entity("ImpactHub.Business.Models.ContatoModel", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContato"));

                    b.Property<int>("Ddd")
                        .HasMaxLength(3)
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Ddi")
                        .HasMaxLength(3)
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdCadastro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusContato")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoContato")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdContato");

                    b.HasIndex("IdCadastro");

                    b.ToTable("TB_IMPACTHUB_CONTATO", (string)null);
                });

            modelBuilder.Entity("ImpactHub.Business.Models.EnderecoModel", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(125)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<int>("IdCadastro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<int>("Numero")
                        .HasMaxLength(5)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdCadastro");

                    b.ToTable("TB_IMPACTHUB_ENDERECO", (string)null);
                });

            modelBuilder.Entity("ImpactHub.Business.Models.LoginModel", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogin"));

                    b.Property<int>("IdCadastro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("StatusLogin")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdLogin");

                    b.HasIndex("IdCadastro")
                        .IsUnique();

                    b.ToTable("TB_IMPACTHUB_LOGIN", (string)null);
                });

            modelBuilder.Entity("ImpactHub.Business.Models.ContatoModel", b =>
                {
                    b.HasOne("ImpactHub.Business.Models.CadastroModel", "Cadastro")
                        .WithMany("Contatos")
                        .HasForeignKey("IdCadastro")
                        .IsRequired();

                    b.Navigation("Cadastro");
                });

            modelBuilder.Entity("ImpactHub.Business.Models.EnderecoModel", b =>
                {
                    b.HasOne("ImpactHub.Business.Models.CadastroModel", "Cadastro")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdCadastro")
                        .IsRequired();

                    b.Navigation("Cadastro");
                });

            modelBuilder.Entity("ImpactHub.Business.Models.LoginModel", b =>
                {
                    b.HasOne("ImpactHub.Business.Models.CadastroModel", "Cadastro")
                        .WithOne("Login")
                        .HasForeignKey("ImpactHub.Business.Models.LoginModel", "IdCadastro")
                        .IsRequired();

                    b.Navigation("Cadastro");
                });

            modelBuilder.Entity("ImpactHub.Business.Models.CadastroModel", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("Login")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
